<a href="https://colab.research.google.com/github/haydarsenoll/pandasrepo/blob/main/numpypandas_adl%C4%B1_not_defterinin_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

data_list = [[1,2,3],[4,5,6]]
array2 = np.array(data_list)
array2


array([[1, 2, 3],
       [4, 5, 6]])

# New Section

In [ ]:
data_list2 = [[5,6,7],[8,9,9]]
ar2 = np.array(data_list2)

In [ ]:
ar2

array([[5, 6, 7],
       [8, 9, 9]])

In [ ]:
np.arange(5,9)

array([5, 6, 7, 8])

In [ ]:
np.arange(5,100,2)
np.ones(5)


array([1., 1., 1., 1., 1.])

In [ ]:
np.linspace(5,100,20)

array([  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
        60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [ ]:
np.eye(5) #birim matris oluşturur

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.randint(0,15,5) #gives 5 random number between 0 and 15

array([ 5, 12,  7, 10,  6])

In [ ]:
np.random.rand(5) # sadece + sayılarını verir

array([0.95684234, 0.51856806, 0.27069347, 0.49844545, 0.22023109])

In [ ]:
np.random.randn(5) # -  ve + sayıları verir

array([ 1.80799073,  0.79185267,  1.00700955, -0.52332655,  0.33670847])

In [ ]:
array = np.arange(1,31)
array.reshape(6,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
NewArray = np.random.randint(0,10,4)
NewArray.max()
NewArray.min()

3

In [ ]:
NewArray = np.random.randint(0,10,4)


In [ ]:
NewArray

array([4, 6, 4, 3])

In [ ]:
NewArray.sum()

17

In [ ]:
NewArray.mean() #ortalamayı verir

4.25

In [ ]:
DetArray = np.random.randint(0,100,25)

In [ ]:
DetArray = DetArray.reshape(5,5)

In [ ]:
DetArray

array([[41, 76, 26, 77, 57],
       [70, 52, 72, 43, 48],
       [70,  0, 70, 48, 63],
       [96,  9, 40, 12, 44],
       [99, 85, 35, 20, 13]])

In [ ]:
np.linalg.det(DetArray)

324601017.00000066

In [ ]:
detArray2 = np.array([[1,2],[3,4]])

In [ ]:
detArray2

array([[1, 2],
       [3, 4]])

In [ ]:
np.linalg.det(detArray2)

-2.0000000000000004

In [ ]:
round(np.linalg.det(detArray2))

-2

In [ ]:
new_array = np.arange(1,21)
new_array.reshape(5,4)
new_array = new_array.reshape(5,4)
new_array[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
arrayy = np.arange(1,6)

In [ ]:
arrayy < 3

array([ True,  True, False, False, False])

In [ ]:
array1 = np.array([1,2,3,4,5,6,7])
array2 = np.array([10,20,30,40,50,60,70])
(array1 + 10)  + (array2 + 20)

array([ 41,  52,  63,  74,  85,  96, 107])

In [ ]:
array1 / 3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        , 2.33333333])

In [ ]:
np.sqrt(array1 )

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131])

In [ ]:
array1 = np.arange(1,17)
array1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
import numpy as np
np.linalg.det(np.arange(1,17).reshape(4,4))

0.0

In [ ]:
import numpy as np
import pandas as pd
labels_list = ["haydar","şenol"]
data_list = [10,20]

In [ ]:
pd.Series(data_list,labels_list)

haydar    10
şenol     20
dtype: int64

In [ ]:
Data_dict = {"haydar":10 ,"şenol":20}

In [ ]:
pd.Series(Data_dict)

haydar    10
şenol     20
dtype: int64

In [ ]:
values_2017 = pd.Series([5,10,15,20],["buğday","mısır","kiraz","havuç"])

In [ ]:
values_2017

buğday     5
mısır     10
kiraz     15
havuç     20
dtype: int64

In [ ]:
values_2018 = pd.Series([2,30,40,15],["buğday","mısır","armut","havuç"])


In [ ]:
values_2018

çilek       5
domates    10
armut      15
kivi       20
dtype: int64

In [ ]:
values_2017 + values_2018

armut      NaN
buğday     7.0
havuç     35.0
kiraz      NaN
mısır     40.0
dtype: float64

In [ ]:
import numpy as np
import pandas as pd
from numpy.random import randn
df = pd.DataFrame(data = randn(3,3), index=["A","B","C"],columns=["column1","column2","column3"])


In [ ]:
df

column1   column2   column3
A  0.726451 -1.357886  1.183425
B -0.389926  1.459338 -0.237043
C -1.598188 -0.795177 -0.900786

In [ ]:
df["column1"]

A    0.726451
B   -0.389926
C   -1.598188
Name: column1, dtype: float64

In [ ]:
df[["column1","column2"]]

column1   column2
A  0.726451 -1.357886
B -0.389926  1.459338
C -1.598188 -0.795177

In [ ]:
df.loc[["A","B"]]

column1   column2   column3
A  0.726451 -1.357886  1.183425
B -0.389926  1.459338 -0.237043

In [ ]:
df.loc["A","column1"]

-0.281910456061128

In [ ]:
df["column4"] = pd.Series(randn(3),["A","B","C"])

In [ ]:
df

column1   column2   column3   column4         D
A  0.726451 -1.357886  1.183425  0.953837  0.140225
B -0.389926  1.459338 -0.237043 -1.379699 -1.201309
C -1.598188 -0.795177 -0.900786 -0.171593 -0.635016

In [ ]:
df["total"] = df["column4"] + df["column3"] + df["column2"] + df["column1"]

In [ ]:
df

column1   column2   column3   column4         D     total
A  0.726451 -1.357886  1.183425  0.953837  0.140225  1.505826
B -0.389926  1.459338 -0.237043 -1.379699 -1.201309 -0.547330
C -1.598188 -0.795177 -0.900786 -0.171593 -0.635016 -3.465743

In [ ]:
df.drop("D",axis=1,inplace =True)

In [ ]:
df

column1   column2   column3   column4     total
A  0.726451 -1.357886  1.183425  0.953837  1.505826
B -0.389926  1.459338 -0.237043 -1.379699 -0.547330
C -1.598188 -0.795177 -0.900786 -0.171593 -3.465743

In [ ]:
df.drop("A",axis=0,inplace =True)

In [ ]:
df.loc[["A","B"],["column1","column2"]]

NameError: ignored

In [ ]:
df

In [ ]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [ ]:
df = pd.DataFrame(randn(4,3),["A","B","C","D"],["column1","column2","column3"])

In [ ]:
df > -1

column1  column2  column3
A     True     True    False
B     True     True     True
C     True     True    False
D    False     True     True

In [ ]:
df[df> -1]

column1   column2   column3
A -0.655592  1.294159 -0.780716
B -0.840593 -0.923081  0.149341
C       NaN -0.641476       NaN
D       NaN       NaN  0.010804

In [ ]:
df[df["column1"] > 1]

Empty DataFrame
Columns: [column1, column2, column3]
Index: []

In [ ]:
df[(df["column2"] > -1) & (df["column1"] > -1) ]

column1   column2   column3
A -0.655592  1.294159 -0.780716
B -0.840593 -0.923081  0.149341

In [ ]:
df[(df["column2"] > -1) | (df["column1"] > -1) ]

column1   column2   column3
A -0.655592  1.294159 -0.780716
B -0.840593 -0.923081  0.149341
C -1.636772 -0.641476 -1.029088

In [ ]:
df["column4"] = randn(4)
df["column5"] = randn(4)

In [ ]:
df.drop("column5",axis=1,inplace=True)


In [ ]:
df

column1   column2   column3   column4   column5
A -0.655592  1.294159 -0.780716 -0.208991  0.776493
B -0.840593 -0.923081  0.149341 -1.037691  0.680288
C -1.636772 -0.641476 -1.029088 -0.590677 -0.412169
D -1.264530 -1.375156  0.010804  0.623004 -1.871020

In [ ]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [ ]:
outerIndex = ["group1","group1","group1","group2","group2","group2","group3","group3","group3"]

In [ ]:
innerIndex = ["Index1","Index2","Index3","Index1","Index2","Index3","Index1","Index2","Index3"]

In [ ]:
list(zip(outerIndex,innerIndex))

[('group1', 'Index1'),
 ('group1', 'Index2'),
 ('group1', 'Index3'),
 ('group2', 'Index1'),
 ('group2', 'Index2'),
 ('group2', 'Index3'),
 ('group3', 'Index1'),
 ('group3', 'Index2'),
 ('group3', 'Index3')]

In [ ]:
hierarchy = list(zip(outerIndex,innerIndex))

In [ ]:
hierarchy = pd.MultiIndex.from_tuples(hierarchy)

In [ ]:
hierarchy

MultiIndex([('group1', 'Index1'),
            ('group1', 'Index2'),
            ('group1', 'Index3'),
            ('group2', 'Index1'),
            ('group2', 'Index2'),
            ('group2', 'Index3'),
            ('group3', 'Index1'),
            ('group3', 'Index2'),
            ('group3', 'Index3')],
           )

In [ ]:
df = pd.DataFrame(randn(9,3),hierarchy,columns = ["column1","column2","column3"])

In [ ]:
df

column1   column2   column3
group1 Index1  0.822960  0.977616  0.261090
       Index2 -0.008008 -1.475788 -0.414699
       Index3 -1.978251 -1.446785 -0.369199
group2 Index1  0.626207  0.248612 -0.106255
       Index2  0.418852  0.373785  0.955300
       Index3  2.099851 -0.728211  2.080503
group3 Index1  0.956527  0.344984  0.526328
       Index2 -1.407187  0.263131 -1.341436
       Index3 -1.968460 -0.072010 -1.935033

In [ ]:
df.loc["group1"]

column1   column2   column3
Index1  0.822960  0.977616  0.261090
Index2 -0.008008 -1.475788 -0.414699
Index3 -1.978251 -1.446785 -0.369199

In [ ]:
df.xs("group1")

column1   column2   column3
Indexes                              
Index1   0.822960  0.977616  0.261090
Index2  -0.008008 -1.475788 -0.414699
Index3  -1.978251 -1.446785 -0.369199

In [ ]:
df.loc[["group1","group2"]]

column1   column2   column3
group1 Index1  0.822960  0.977616  0.261090
       Index2 -0.008008 -1.475788 -0.414699
       Index3 -1.978251 -1.446785 -0.369199
group2 Index1  0.626207  0.248612 -0.106255
       Index2  0.418852  0.373785  0.955300
       Index3  2.099851 -0.728211  2.080503

In [ ]:
df.loc["group1"].loc["Index1"]

column1    0.822960
column2    0.977616
column3    0.261090
Name: Index1, dtype: float64

In [ ]:
df.xs("group1").xs("Index1").xs("column1")

0.8229604234493961

In [ ]:
df.loc["group1"].loc["Index1"]["column1"]

0.8229604234493961

In [ ]:
df.index.names


FrozenList([None, None])

In [ ]:
df.index.names= ["groups","Indexes"]

In [ ]:
df

column1   column2   column3
groups Indexes                              
group1 Index1   0.822960  0.977616  0.261090
       Index2  -0.008008 -1.475788 -0.414699
       Index3  -1.978251 -1.446785 -0.369199
group2 Index1   0.626207  0.248612 -0.106255
       Index2   0.418852  0.373785  0.955300
       Index3   2.099851 -0.728211  2.080503
group3 Index1   0.956527  0.344984  0.526328
       Index2  -1.407187  0.263131 -1.341436
       Index3  -1.968460 -0.072010 -1.935033

In [ ]:
df.xs("Index1",level ="Indexes")

column1   column2   column3
groups                              
group1  0.822960  0.977616  0.261090
group2  0.626207  0.248612 -0.106255
group3  0.956527  0.344984  0.526328

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

arr = np.array([[10,20,np.nan],[5,np.nan,np.nan],[21,np.nan,10]])

In [ ]:
arr

array([[10., 20., nan],
       [ 5., nan, nan],
       [21., nan, 10.]])

In [ ]:
df = pd.DataFrame(arr,index =["Index1","Index2","Index3"],columns = ["column1","column2","column3"] )

In [ ]:
df

column1  column2  column3
Index1     10.0     20.0      NaN
Index2      5.0      NaN      NaN
Index3     21.0      NaN     10.0

In [ ]:
df.dropna()

Empty DataFrame
Columns: [column1, column2, column3]
Index: []

In [ ]:
df.dropna(axis = 1)

column1
Index1     10.0
Index2      5.0
Index3     21.0

In [ ]:
df.dropna(thresh = 2)

column1  column2  column3
Index1     10.0     20.0      NaN
Index3     21.0      NaN     10.0

In [ ]:
df.fillna(value = int(5.3))

column1  column2  column3
Index1     10.0     20.0      5.0
Index2      5.0      5.0      5.0
Index3     21.0      5.0     10.0

In [ ]:
df.fillna(value = 5)

column1  column2  column3
Index1     10.0     20.0      5.0
Index2      5.0      5.0      5.0
Index3     21.0      5.0     10.0

In [ ]:
df.sum()

column1    36.0
column2    20.0
column3    10.0
dtype: float64

In [ ]:
df.sum().sum()

66.0

In [ ]:
df.isnull().sum() #hangi sütunda kaçar tanr NaN olduğunu verir

column1    0
column2    2
column3    2
dtype: int64

In [ ]:
def calculate_mean(df):
  total_Sum = df.sum().sum()
  total_Num = df.size - df.isnull().sum().sum()
  return total_Sum / total_Num

In [ ]:
df.fillna(value = calculate_mean(df), inplace = True)

In [ ]:
df

column1  column2  column3
Index1     10.0     20.0     13.2
Index2      5.0     13.2     13.2
Index3     21.0     13.2     10.0

In [ ]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [ ]:
dataset = {"Departman":["bilişim","bilişim","mühendis","öğretmen","öğretmen","mühendis"], "Çalışan": ["haydar","furkan","mehmet","ipek","yasemin","ibrahim"],"Maaş":[500,300,200,600,700,1000]}

In [ ]:
df = pd.DataFrame(dataset)

In [ ]:
df

Departman  Çalışan  Maaş
0   bilişim   haydar   500
1   bilişim   furkan   300
2  mühendis   mehmet   200
3  öğretmen     ipek   600
4  öğretmen  yasemin   700

In [ ]:
depGroup = df.groupby("Departman")

In [ ]:
depGroup.sum()

<ipython-input-95-e910d1468b12>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  depGroup.sum()


Maaş
Departman      
bilişim     800
mühendis    200
öğretmen   1300

In [ ]:
depGroup.sum().loc["mühendis"]

<ipython-input-104-bcd3db9e18d6>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  depGroup.sum().loc["mühendis"]


Maaş    1200
Name: mühendis, dtype: int64

In [ ]:
df.groupby("Departman").count()

Çalışan  Maaş
Departman               
bilişim          2     2
mühendis         2     2
öğretmen         2     2

In [ ]:
df.groupby("Departman").max()

Çalışan  Maaş
Departman               
bilişim     haydar   500
mühendis    mehmet  1000
öğretmen   yasemin   700

In [ ]:
df.groupby("Departman").min()

Çalışan  Maaş
Departman               
bilişim     furkan   300
mühendis   ibrahim   200
öğretmen      ipek   600

In [ ]:
df.groupby("Departman").mean()

<ipython-input-118-62191409fe80>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby("Departman").mean()


Maaş
Departman       
bilişim    400.0
mühendis   600.0
öğretmen   650.0

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from numpy.random import randn

In [ ]:
dataset1 = {
    "A": ["A1","A2","A3","A4"],
    "B":["B1","B2","B3","B4"],
    "C":["C1","C2","C3","C4"],
}
dataset2 = {
    "A": ["A5","A6","A7","A8"],
    "B":["B5","B6","B7","B8"],
    "C":["C5","C6","C7","C8"],
}

In [ ]:
df1 = pd.DataFrame(dataset1,index = [1,2,3,4])
df2 = pd.DataFrame(dataset2,index = [5,6,7,8] )

In [ ]:
df1

A   B   C
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
4  A4  B4  C4

In [ ]:
df2

A   B   C
5  A5  B5  C5
6  A6  B6  C6
7  A7  B7  C7
8  A8  B8  C8

In [ ]:
pd.concat([df1,df2])

A   B   C
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
4  A4  B4  C4
5  A5  B5  C5
6  A6  B6  C6
7  A7  B7  C7
8  A8  B8  C8

In [ ]:
dataset1 = {
    "A" : ["A1","A2","A3"],
    "B" : ["B1","B2","B3"],

}

In [ ]:
dataset2 = {
    "X" : ["X1","X2","X3","X4"],
    "Y" : ["Y1","Y2","Y3","Y4"],

}

In [ ]:
df1 = pd.DataFrame(dataset1,index = [1,2,3])
df2 = pd.DataFrame(dataset2,index = [1,2,3,4])

In [ ]:
df1

A   B anahtar
1  A1  B1      K1
2  A2  B2      K2
3  A3  B3      K3

In [ ]:
df1.join(df2) #sqldeki left join

A   B   X   Y
1  A1  B1  X1  Y1
2  A2  B2  X2  Y2
3  A3  B3  X3  Y3

In [ ]:
df2.join(df1) #sqldeki right join

X   Y    A    B
1  X1  Y1   A1   B1
2  X2  Y2   A2   B2
3  X3  Y3   A3   B3
4  X4  Y4  NaN  NaN

In [ ]:
dataset1 = {
    "A" : ["A1","A2","A3"],
    "B" : ["B1","B2","B3"],
    "anahtar" : ["K1","K2","K3"]
}
dataset2 = {
    "X" : ["X1","X2","X3","X4"],
    "Y" : ["Y1","Y2","Y3","Y4"],
    "anahtar" : ["K1","K2","K5","K4"]
}
df1 = pd.DataFrame(dataset1,index = [1,2,3])
df2 = pd.DataFrame(dataset2,index = [1,2,3,4])

In [ ]:
df1


A   B anahtar
1  A1  B1      K1
2  A2  B2      K2
3  A3  B3      K3

In [ ]:
df2

X   Y anahtar
1  X1  Y1      K1
2  X2  Y2      K2
3  X3  Y3      K5
4  X4  Y4      K4

In [ ]:
pd.merge(df1,df2) #INNER JOIN


A   B anahtar   X   Y
0  A1  B1      K1  X1  Y1
1  A2  B2      K2  X2  Y2

In [ ]:
pd.merge(df1,df2,on ="anahtar")

A   B anahtar   X   Y
0  A1  B1      K1  X1  Y1
1  A2  B2      K2  X2  Y2